name: full_store_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #language 
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Core
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.10

#dart run build_runner build --delete-conflicting-outputs
  #Firebase
  firebase_core: ^2.24.2
  #animation package
  animate_do: ^3.3.4
  #change app name package
  rename_app: ^1.6.2
  #shared preferences
  shared_preferences: ^2.3.5
  #Flutter Bloc
  flutter_bloc: ^9.0.0
  #freezed annotation
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/play_store_512.png"


flutter:

  uses-material-design: true


  assets:
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/


  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
